version: '3.8'

services:

  postgres:
    image: postgres
    container_name: ${PG_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      postgres -c logging_collector=on
               -c log_directory=/var/log/postgresql
               -c log_destination=stderr

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
      - "15432:${PGADMIN_LISTEN_PORT}"
    depends_on:
      - postgres

  frontend:
    image: nginx
    container_name: web
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "5500:5500"
    volumes:
      - ../../frontend/static:/usr/share/nginx/html/

volumes:
  postgres:
  pgadmin:
  frontend:
