"""updete relationship User - Tweet

Revision ID: e613593a1487
Revises: 6a7f4b25fc0f
Create Date: 2023-10-07 23:58:01.712944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e613593a1487"
down_revision: Union[str, None] = "6a7f4b25fc0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tweets_tab", "author", new_column_name="author_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tweets_tab", "author_id", new_column_name="author")
    # ### end Alembic commands ###
