"""Follow key pairs made unique

Revision ID: 798fcab40b4b
Revises: c096c24e1437
Create Date: 2023-10-04 22:18:08.775676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "798fcab40b4b"
down_revision: Union[str, None] = "c096c24e1437"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "follows_tab", ["user_id", "follow_user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "follows_tab", type_="unique")
    # ### end Alembic commands ###
